<?php

namespace App\Helpers;

class CountryHelper
{
    /**
     * Map nationality names to ISO 3166-1 alpha-2 country codes
     * for flag display purposes
     */
    public static function getNationalityCountryCode($nationality)
    {
        // First try country names mapping
        $countryNameMap = [
            'Afghanistan' => 'af',
            'Albania' => 'al',
            'Algeria' => 'dz',
            'United States' => 'us',
            'United States of America' => 'us',
            'USA' => 'us',
            'Andorra' => 'ad',
            'Angola' => 'ao',
            'Antigua and Barbuda' => 'ag',
            'Argentina' => 'ar',
            'Armenia' => 'am',
            'Australia' => 'au',
            'Austria' => 'at',
            'Azerbaijan' => 'az',
            'Bahamas' => 'bs',
            'Bahrain' => 'bh',
            'Bangladesh' => 'bd',
            'Barbados' => 'bb',
            'Belarus' => 'by',
            'Belgium' => 'be',
            'Belize' => 'bz',
            'Benin' => 'bj',
            'Bhutan' => 'bt',
            'Bolivia' => 'bo',
            'Bosnia and Herzegovina' => 'ba',
            'Botswana' => 'bw',
            'Brazil' => 'br',
            'United Kingdom' => 'gb',
            'UK' => 'gb',
            'Great Britain' => 'gb',
            'Brunei' => 'bn',
            'Bulgaria' => 'bg',
            'Burkina Faso' => 'bf',
            'Myanmar' => 'mm',
            'Burma' => 'mm',
            'Burundi' => 'bi',
            'Cambodia' => 'kh',
            'Cameroon' => 'cm',
            'Canada' => 'ca',
            'Cape Verde' => 'cv',
            'Central African Republic' => 'cf',
            'Chad' => 'td',
            'Chile' => 'cl',
            'China' => 'cn',
            'Colombia' => 'co',
            'Comoros' => 'km',
            'Congo' => 'cd',
            'Costa Rica' => 'cr',
            'Croatia' => 'hr',
            'Cuba' => 'cu',
            'Cyprus' => 'cy',
            'Czech Republic' => 'cz',
            'Denmark' => 'dk',
            'Djibouti' => 'dj',
            'Dominican Republic' => 'do',
            'Netherlands' => 'nl',
            'East Timor' => 'tl',
            'Ecuador' => 'ec',
            'Egypt' => 'eg',
            'United Arab Emirates' => 'ae',
            'UAE' => 'ae',
            'Equatorial Guinea' => 'gq',
            'Eritrea' => 'er',
            'Estonia' => 'ee',
            'Ethiopia' => 'et',
            'Fiji' => 'fj',
            'Philippines' => 'ph',
            'Finland' => 'fi',
            'France' => 'fr',
            'Gabon' => 'ga',
            'Gambia' => 'gm',
            'Georgia' => 'ge',
            'Germany' => 'de',
            'Ghana' => 'gh',
            'Greece' => 'gr',
            'Grenada' => 'gd',
            'Guatemala' => 'gt',
            'Guinea-Bissau' => 'gw',
            'Guinea' => 'gn',
            'Guyana' => 'gy',
            'Haiti' => 'ht',
            'Honduras' => 'hn',
            'Hungary' => 'hu',
            'Iceland' => 'is',
            'India' => 'in',
            'Indonesia' => 'id',
            'Iran' => 'ir',
            'Iraq' => 'iq',
            'Ireland' => 'ie',
            'Israel' => 'il',
            'Italy' => 'it',
            'Ivory Coast' => 'ci',
            'Jamaica' => 'jm',
            'Japan' => 'jp',
            'Jordan' => 'jo',
            'Kazakhstan' => 'kz',
            'Kenya' => 'ke',
            'Saint Kitts and Nevis' => 'kn',
            'Kuwait' => 'kw',
            'Kyrgyzstan' => 'kg',
            'Laos' => 'la',
            'Latvia' => 'lv',
            'Lebanon' => 'lb',
            'Liberia' => 'lr',
            'Libya' => 'ly',
            'Liechtenstein' => 'li',
            'Lithuania' => 'lt',
            'Luxembourg' => 'lu',
            'Macedonia' => 'mk',
            'Madagascar' => 'mg',
            'Malawi' => 'mw',
            'Malaysia' => 'my',
            'Maldives' => 'mv',
            'Mali' => 'ml',
            'Malta' => 'mt',
            'Marshall Islands' => 'mh',
            'Mauritania' => 'mr',
            'Mauritius' => 'mu',
            'Mexico' => 'mx',
            'Micronesia' => 'fm',
            'Moldova' => 'md',
            'Monaco' => 'mc',
            'Mongolia' => 'mn',
            'Morocco' => 'ma',
            'Lesotho' => 'ls',
            'Mozambique' => 'mz',
            'Namibia' => 'na',
            'Nauru' => 'nr',
            'Nepal' => 'np',
            'New Zealand' => 'nz',
            'Vanuatu' => 'vu',
            'Nicaragua' => 'ni',
            'Nigeria' => 'ng',
            'Niger' => 'ne',
            'North Korea' => 'kp',
            'Norway' => 'no',
            'Oman' => 'om',
            'Pakistan' => 'pk',
            'Palau' => 'pw',
            'Panama' => 'pa',
            'Papua New Guinea' => 'pg',
            'Paraguay' => 'py',
            'Peru' => 'pe',
            'Poland' => 'pl',
            'Portugal' => 'pt',
            'Qatar' => 'qa',
            'Romania' => 'ro',
            'Russia' => 'ru',
            'Rwanda' => 'rw',
            'Saint Lucia' => 'lc',
            'El Salvador' => 'sv',
            'Samoa' => 'ws',
            'San Marino' => 'sm',
            'Sao Tome and Principe' => 'st',
            'Saudi Arabia' => 'sa',
            'Senegal' => 'sn',
            'Serbia' => 'rs',
            'Seychelles' => 'sc',
            'Sierra Leone' => 'sl',
            'Singapore' => 'sg',
            'Slovakia' => 'sk',
            'Slovenia' => 'si',
            'Solomon Islands' => 'sb',
            'Somalia' => 'so',
            'South Africa' => 'za',
            'South Korea' => 'kr',
            'Spain' => 'es',
            'Sri Lanka' => 'lk',
            'Sudan' => 'sd',
            'Suriname' => 'sr',
            'Swaziland' => 'sz',
            'Sweden' => 'se',
            'Switzerland' => 'ch',
            'Syria' => 'sy',
            'Taiwan' => 'tw',
            'Tajikistan' => 'tj',
            'Tanzania' => 'tz',
            'Thailand' => 'th',
            'Togo' => 'tg',
            'Tonga' => 'to',
            'Trinidad and Tobago' => 'tt',
            'Tunisia' => 'tn',
            'Turkey' => 'tr',
            'Tuvalu' => 'tv',
            'Uganda' => 'ug',
            'Ukraine' => 'ua',
            'Uruguay' => 'uy',
            'Uzbekistan' => 'uz',
            'Venezuela' => 've',
            'Vietnam' => 'vn',
            'Yemen' => 'ye',
            'Zambia' => 'zm',
            'Zimbabwe' => 'zw'
        ];

        // Check if it's a country name first
        $normalizedInput = ucwords(strtolower(trim($nationality)));
        if (isset($countryNameMap[$normalizedInput])) {
            return $countryNameMap[$normalizedInput];
        }

        // Fall back to nationality adjectives mapping
        $nationalityMap = [
            'Afghan' => 'af',
            'Albanian' => 'al',
            'Algerian' => 'dz',
            'American' => 'us',
            'Andorran' => 'ad',
            'Angolan' => 'ao',
            'Antiguan' => 'ag',
            'Argentine' => 'ar',
            'Armenian' => 'am',
            'Australian' => 'au',
            'Austrian' => 'at',
            'Azerbaijani' => 'az',
            'Bahamian' => 'bs',
            'Bahraini' => 'bh',
            'Bangladeshi' => 'bd',
            'Barbadian' => 'bb',
            'Belarusian' => 'by',
            'Belgian' => 'be',
            'Belizean' => 'bz',
            'Beninese' => 'bj',
            'Bhutanese' => 'bt',
            'Bolivian' => 'bo',
            'Bosnian' => 'ba',
            'Botswanan' => 'bw',
            'Brazilian' => 'br',
            'British' => 'gb',
            'Bruneian' => 'bn',
            'Bulgarian' => 'bg',
            'Burkinabe' => 'bf',
            'Burmese' => 'mm',
            'Burundian' => 'bi',
            'Cambodian' => 'kh',
            'Cameroonian' => 'cm',
            'Canadian' => 'ca',
            'Cape Verdean' => 'cv',
            'Central African' => 'cf',
            'Chadian' => 'td',
            'Chilean' => 'cl',
            'Chinese' => 'cn',
            'Colombian' => 'co',
            'Comoran' => 'km',
            'Congolese' => 'cd',
            'Costa Rican' => 'cr',
            'Croatian' => 'hr',
            'Cuban' => 'cu',
            'Cypriot' => 'cy',
            'Czech' => 'cz',
            'Danish' => 'dk',
            'Djiboutian' => 'dj',
            'Dominican' => 'do',
            'Dutch' => 'nl',
            'East Timorese' => 'tl',
            'Ecuadorean' => 'ec',
            'Egyptian' => 'eg',
            'Emirian' => 'ae',
            'Equatorial Guinean' => 'gq',
            'Eritrean' => 'er',
            'Estonian' => 'ee',
            'Ethiopian' => 'et',
            'Fijian' => 'fj',
            'Filipino' => 'ph',
            'Finnish' => 'fi',
            'French' => 'fr',
            'Gabonese' => 'ga',
            'Gambian' => 'gm',
            'Georgian' => 'ge',
            'German' => 'de',
            'Ghanaian' => 'gh',
            'Greek' => 'gr',
            'Grenadian' => 'gd',
            'Guatemalan' => 'gt',
            'Guinea-Bissauan' => 'gw',
            'Guinean' => 'gn',
            'Guyanese' => 'gy',
            'Haitian' => 'ht',
            'Herzegovinian' => 'ba',
            'Honduran' => 'hn',
            'Hungarian' => 'hu',
            'Icelander' => 'is',
            'Indian' => 'in',
            'Indonesian' => 'id',
            'Iranian' => 'ir',
            'Iraqi' => 'iq',
            'Irish' => 'ie',
            'Israeli' => 'il',
            'Italian' => 'it',
            'Ivorian' => 'ci',
            'Jamaican' => 'jm',
            'Japanese' => 'jp',
            'Jordanian' => 'jo',
            'Kazakhstani' => 'kz',
            'Kenyan' => 'ke',
            'Kittian and Nevisian' => 'kn',
            'Kuwaiti' => 'kw',
            'Kyrgyz' => 'kg',
            'Laotian' => 'la',
            'Latvian' => 'lv',
            'Lebanese' => 'lb',
            'Liberian' => 'lr',
            'Libyan' => 'ly',
            'Liechtensteiner' => 'li',
            'Lithuanian' => 'lt',
            'Luxembourgish' => 'lu',
            'Macedonian' => 'mk',
            'Malagasy' => 'mg',
            'Malawian' => 'mw',
            'Malaysian' => 'my',
            'Maldivan' => 'mv',
            'Malian' => 'ml',
            'Maltese' => 'mt',
            'Marshallese' => 'mh',
            'Mauritanian' => 'mr',
            'Mauritian' => 'mu',
            'Mexican' => 'mx',
            'Micronesian' => 'fm',
            'Moldovan' => 'md',
            'Monacan' => 'mc',
            'Mongolian' => 'mn',
            'Moroccan' => 'ma',
            'Mosotho' => 'ls',
            'Motswana' => 'bw',
            'Mozambican' => 'mz',
            'Namibian' => 'na',
            'Nauruan' => 'nr',
            'Nepalese' => 'np',
            'New Zealander' => 'nz',
            'Ni-Vanuatu' => 'vu',
            'Nicaraguan' => 'ni',
            'Nigerian' => 'ng',
            'Nigerien' => 'ne',
            'North Korean' => 'kp',
            'Northern Irish' => 'gb',
            'Norwegian' => 'no',
            'Omani' => 'om',
            'Pakistani' => 'pk',
            'Palauan' => 'pw',
            'Panamanian' => 'pa',
            'Papua New Guinean' => 'pg',
            'Paraguayan' => 'py',
            'Peruvian' => 'pe',
            'Polish' => 'pl',
            'Portuguese' => 'pt',
            'Qatari' => 'qa',
            'Romanian' => 'ro',
            'Russian' => 'ru',
            'Rwandan' => 'rw',
            'Saint Lucian' => 'lc',
            'Salvadoran' => 'sv',
            'Samoan' => 'ws',
            'San Marinese' => 'sm',
            'Sao Tomean' => 'st',
            'Saudi' => 'sa',
            'Saudi Arabian' => 'sa',
            'Scottish' => 'gb',
            'Senegalese' => 'sn',
            'Serbian' => 'rs',
            'Seychellois' => 'sc',
            'Sierra Leonean' => 'sl',
            'Singaporean' => 'sg',
            'Slovakian' => 'sk',
            'Slovenian' => 'si',
            'Solomon Islander' => 'sb',
            'Somali' => 'so',
            'South African' => 'za',
            'South Korean' => 'kr',
            'Spanish' => 'es',
            'Sri Lankan' => 'lk',
            'Sudanese' => 'sd',
            'Surinamese' => 'sr',
            'Swazi' => 'sz',
            'Swedish' => 'se',
            'Swiss' => 'ch',
            'Syrian' => 'sy',
            'Taiwanese' => 'tw',
            'Tajik' => 'tj',
            'Tanzanian' => 'tz',
            'Thai' => 'th',
            'Togolese' => 'tg',
            'Tongan' => 'to',
            'Trinidadian or Tobagonian' => 'tt',
            'Tunisian' => 'tn',
            'Turkish' => 'tr',
            'Tuvaluan' => 'tv',
            'Ugandan' => 'ug',
            'Ukrainian' => 'ua',
            'Uruguayan' => 'uy',
            'Uzbekistani' => 'uz',
            'Venezuelan' => 've',
            'Vietnamese' => 'vn',
            'Welsh' => 'gb',
            'Yemenite' => 'ye',
            'Zambian' => 'zm',
            'Zimbabwean' => 'zw'
        ];

        // Check nationality adjectives as fallback
        $normalizedNationality = ucwords(strtolower(trim($nationality)));
        return $nationalityMap[$normalizedNationality] ?? 'un'; // UN flag as fallback
    }

    /**
     * Get flag emoji for the nationality (primary method)
     */
    public static function getFlagEmoji($nationality)
    {
        $countryCode = strtoupper(self::getNationalityCountryCode($nationality));
        
        if ($countryCode === 'UN') {
            return '🌐'; // Globe emoji for unknown
        }
        
        // Convert country code to flag emoji
        $flagEmoji = '';
        for ($i = 0; $i < strlen($countryCode); $i++) {
            $flagEmoji .= mb_chr(ord($countryCode[$i]) + 127397, 'UTF-8');
        }
        
        return $flagEmoji;
    }
}
